spring.application.name=adhesion-app
server.port=8082


# =============================
# DATABASE CONFIG
# =============================
spring.datasource.url=jdbc:postgresql://localhost:5432/adhesion_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver



# =============================
# JPA / HIBERNATE
# =============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# =============================
# LOGGING
# =============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Enable detailed error messages
server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always
server.error.include-binding-errors=always

# =============================
# GEMINI AI CONFIGURATION
# =============================
gemini.api.key=AIzaSyDLlw_9bC1q9nVPyu5Rj0suvPJiGqnjuDA
gemini.model=gemini-flash-latest
gemini.max-tokens=1000